# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vbguest.auto_update = false

    config.vm.box = "bento/almalinux-8.4"

    config.vm.provision "shell", inline: <<-SHELL

        setenforce 0

        sed -i 's/SELINUX=enforcing/SELINUX=permissive/g' /etc/selinux/config
        
        echo "root:gprm8350" | sudo chpasswd
        
        echo 'options kvm_intel nested=1' >> /etc/modprobe.d/kvm.conf
        modprobe -r kvm_intel
        modprobe kvm_intel
        cat /sys/module/kvm_intel/parameters/nested
        modinfo kvm_intel | grep -i nested

        dnf --assumeyes --nogpgcheck install \
            haproxy \
            keepalived git vim wget curl cloud-utils-growpart gdisk

        sysctl --system

        dnf --assumeyes remove -y postfix > /dev/null 2>&1

        dd if=/dev/zero of=/EMPTY bs=1M
        rm -f /EMPTY

        sync

    SHELL

end
